### ISSUE TITLE
error starting up

### ISSUE THREAD

**Issue by anthonymobile** [satterly/athena-cli#8]
user error?

`athena --profile default --region us-east-1 --schema myschema`

produces

`An error occurred (InvalidRequestException) when calling the StartQueryExecution operation: line 1:9: mismatched input '<EOF>'. Expecting: 'ALTER', 'ANALYZE', 'CALL', 'COMMIT', 'CREATE', 'DEALLOCATE', 'DELETE', 'DESC', 'DESCRIBE', 'DROP', 'EXECUTE', 'EXPLAIN', 'GRANT', 'INSERT', 'PREPARE', 'RESET', 'REVOKE', 'ROLLBACK', 'SET', 'SHOW', 'START', 'UNLOAD', 'UPDATE', 'USE', <query>`

but athena-cli works fine with the schema afterwards

**Comment by satterly** [comment]
Fixed by 40b7d07113f4523823f9b15fadd680e87c3d80e0
